name: data-science-workshop
channels:
  - conda-forge
dependencies:
  # Jupyter
  - notebook=5.7.8
  - tornado=5.1.1
  - nbconvert=5.4
  - widgetsnbextension=3.4
  # Python Kernel
  - numpy==1.16.4
  - statsmodels==0.9.0
  - scikit-learn==0.21.2
  - scipy==1.2.1
  - matplotlib==3.1.0
  - seaborn==0.9.0
  - pandas==0.24.2
  - pandas-profiling==2.1.0
  - bokeh==1.2.0
  - hvplot==0.4.0