#!/usr/bin/env bash
set -e
DATASET_FOLDER=data
#URL_DATASET=https://www.dropbox.com/sh/xfbxcs7w5im3j34/AABUeyTe83uy_lZxoXZcGDuxa?dl=1
#URL_DATASET_PRE=https://www.dropbox.com/sh/gjfjso2g7dwm0pe/AADjH-HlnsgzJU3ajO8VTCWsa?dl=1
#URL_DATASET_RAW=https://www.dropbox.com/sh/ivjvn7nkoqfpyvn/AACrw0khExAa8RVl8eWsKhdea?dl=1
#URL_DATASET_READY=https://www.dropbox.com/sh/ncda59u6zrjtjji/AADUFeXCHDPUZxnH0xFBeN63a?dl=1
#URL_DATASET_PRE=https://www.dropbox.com/s/dnijxrlso7dxpd7/dataset_preprocessed.csv?dl=0
URL_DATASET_PRE=https://www.dropbox.com/s/hdimpjzv136oh8d/join_preprocessed.csv?dl=0
URL_DATASET_READY=https://www.dropbox.com/s/uu7doww3ko75kyi/dataset_ready.csv?dl=0

#mkdir -p $DATASET_FOLDER/preprocessed/
#mkdir -p $DATASET_FOLDER/ready/
mkdir -p $DATASET_FOLDER

wget -O $DATASET_FOLDER/join_preprocessed.csv $URL_DATASET_PRE
wget -O $DATASET_FOLDER/dataset_ready.csv $URL_DATASET_READY

exec "$@"
