#!/usr/bin/env bash
set -e
TMP_FOLDER=tmp
DATASET_FOLDER=data
URL_DATASET=https://www.dropbox.com/sh/xfbxcs7w5im3j34/AABUeyTe83uy_lZxoXZcGDuxa?dl=1
URL_DATASET_PRE=https://www.dropbox.com/sh/gjfjso2g7dwm0pe/AADjH-HlnsgzJU3ajO8VTCWsa?dl=1
URL_DATASET_RAW=https://www.dropbox.com/sh/ivjvn7nkoqfpyvn/AACrw0khExAa8RVl8eWsKhdea?dl=1
URL_DATASET_READY=https://www.dropbox.com/sh/ncda59u6zrjtjji/AADUFeXCHDPUZxnH0xFBeN63a?dl=1

if [ ! -d $TMP_FOLDER ]
then
  mkdir $TMP_FOLDER
fi

wget -O $TMP_FOLDER/dataset_pre.zip $URL_DATASET_PRE
wget -O $TMP_FOLDER/dataset_ready.zip $URL_DATASET_READY
wget -O $TMP_FOLDER/dataset_raw.zip $URL_DATASET_RAW
unzip -o $TMP_FOLDER/dataset_pre.zip -d $DATASET_FOLDER/preprocessed
unzip -o $TMP_FOLDER/dataset_ready.zip -d $DATASET_FOLDER/ready
unzip -o $TMP_FOLDER/dataset_raw.zip -d $DATASET_FOLDER/raw

rm -rf $TMP_FOLDER
exec "$@"
